name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop -v '>= 1.0, < 2.0' # https://docs.rubocop.org/en/stable/installation/
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.rubocop.yml
      - name: Rubocop Report
        run: rubocop --color

  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@16.x stylelint-scss@4.x stylelint-config-standard@29.x stylelint-config-tailwindcss@0.0.7 postcss@8.x
          [ -f .stylelintrc.json ] || echo '{
            "extends": [
              "stylelint-config-standard",
              "stylelint-config-tailwindcss"
            ],
            "rules": {
              "function-no-unknown": null,
              "at-rule-no-unknown": null
            }
          }' > .stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"

  nodechecker:
    name: Node Modules Checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then
            echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."
            echo -e "\e[1;32mYou can set up a .gitignore file with this folder included to prevent this from happening in the future."
            exit 1
          fi
